---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    AllCops:
      TargetRubyVersion: 2.2
ratings:
  paths:
    - "**.rb"
